# Generated by Django 5.1.15 on 2026-07-27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0007_alter_question_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
